---
title: "Data communication through Health Level 7"
author: "Omar Sprockel"
date: '2022-12-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Introduction}
#During my studies I worked at UMC Utrecht as a student assistant in some of the labs. Something that I always found to be inefficiënt is the fact that patiënt material was always given in combination with a document. The document stated information about the patiënt and which tests needed to be performed on the material given. These documents were mostly generated by doctors in their software called HiX. The information on the document was always typed by hand, so the same test could always be described in different ways. The patiënt information and requested tests have to be copied by hand into the laboratory software called GLIMS.

#For this project I had the idea to make a proof on concept for automatisation of this process. This would be done by creating a platform through R Shiny with checkboxes. The checkboxes would be categorised by patiënt material type, and possible tests for each type. The idea was for the doctors to click each test that was needed, which would create an output that could be used as an input for GLIMS. This way the information would no longer have to be copied by hand which would reduce errors and time needed.

#I got to work by talking with employees working with the GLIMS environment. I learned the different type of tests possible for some patient materials and how the process went from the doctors request until the result.

#After having a solid foundation about the practical side of things I booked a meeting with some connections at ICT. These are the people who are very knowledgable about the coding side of GLIMS and are able to make changes to the way it works. I explained my idea for the project and asked for information regarding the possibility of my ideas.

#I learned that there were already actual projects running to realise exactly that which I had imagined, albeit using different tools. The issue with my idea however was the fact that GLIMS runs on a specific coding software called MISPL. If I were to create the platform for the doctors in R Shiny each output would need to be translated to MISPL code in order to make it readable. This would be so much work that I would be far from having anything working to show after the 40 hours supplied for this project.

#As an alternative I was informed about another project running which was to communicate information from GLIMS to another piece of software called OpenSpecimen. OpenSpecimen is used to process and store information about samples for studies. A lot of studies had been performed with the use of GLIMS and now had to be moved over to OpenSpecimen.

#In order to realise this, code would have to be generated for a programming language called Health Level 7 (HL7). Health Level 7 is a worldwide coding language used by hospitals for communication of patient data in a standardised way. I was asked to help by writing part of the code responsible for letting the system know which part of the code supplied which information, also known as the "header".

#I dove into the theory about how HL7 works and what certain terms mean. The header needed to contain:

#An MSH, which defines the purpose, location, destination, and a few extra's concerning the message sent.
#A PID, patient ID containing information about the patient that usually doesn't change (sex, date of birth, etc).
#An SPM, which contains information that is unique to certain samples.
#An OBR, containing information specific to the order sent.
#An ORC, which supplies information that is relevant to most orders
#And an OBX, used to transmit a single observation, relevant to an order.

#So I got to work and started building the header for the message. Down below I will link 2 of the headers that I wrote.
```

```{r HL7 headers, eval = FALSE}
#Header 1
MSH|^~\&|Glims|UMC-Utrecht|OpenSpecimen|UMC-Utrecht|20220802210400||OUL^R22|000012627500|P|2.5|||NE|AL||8859/15
PID|1||5602460^^^UMCU_I||Spruit^^^^L||19760203|F||||||||||||||||N||||||N
SPM|1|229900280000&GLIMS||CC-BL-DUM-0-00-STB0^Nonexisting^Tube^GLIMS||||||||0^mL&mL&GLIMS|||||20220802210300|20220802210400||Y
OBR|1||986229900280^GLIMS|Studie_22qPsych-Patient-P^22qPsych Patient^GLIMS|||20220802210300|||||||||LISDLA^Glims - Kcl&&Glims - Kcl^^^^^^hcpr^UMCU_I||||||20220802210400||CDL|F||^^^20220802210300^^R
ORC|SC||986229900280^GLIMS||CM||^^^20220802210300^^R||20220802210400|||LISDLA^Glims - Kcl&&Glims - Kcl^^^^^^hcpr^UMCU_I|ST657^^^^^^^^^^GLIMS||||CDL^CDL^GLIMS
OBX|1|ST|Studie^Studie^GLIMS||22qPsych Patient|||-|||F|||20220802210300|DLA^DLA^GLIMS||||
SPM|2|229900280001&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210300|20220802210400||Y
SPM|3|229900280002&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210300|20220802210400||Y
SPM|4|229900280003&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210300|20220802210400||Y
SPM|5|229900280004&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210300|20220802210400||Y
SPM|6|229900280005&GLIMS||CC-BL-S0-0-00-STB0^Stolbloed (rood) 10 ml/Stolbloed/rood, CAT 10 ml^GLIMS||||||||3.5^mL%mL&GLIMS|||||20220802210300|20220802210400||Y


#Header 2
MSH|^~\&|Glims|UMC-Utrecht|OpenSpecimen|UMC-Utrecht|20220802210700||OUL^R22|000012627500|P|2.5|||NE|AL||8859/15
PID|1||5602460^^^UMCU_I||Spruit^^^^L||19760203|M||||||||||||||||N||||||N
SPM|1|229900281000&GLIMS||CC-BL-DUM-0-00-STB0^Nonexisting^Tube^GLIMS||||||||0^mL&mL&GLIMS|||||20220802210600|20220802210700||Y
OBR|1||986229900281^GLIMS|Studie_22qPsych-Patient-P^22qPsych Patient^GLIMS|||20220802210600|||||||||LISDLA^Glims - Kcl&&Glims - Kcl^^^^^^hcpr^UMCU_I||||||20220802210700||CDL|F||^^^20220802210600^^R
ORC|SC||986229900281^GLIMS||CM||^^^20220802210600^^R||20220802210700|||LISDLA^Glims - Kcl&&Glims - Kcl^^^^^^hcpr^UMCU_I|ST657^^^^^^^^^^GLIMS||||CDL^CDL^GLIMS
OBX|1|ST|Studie^Studie^GLIMS||22qPsych Patient|||-|||F|||20220802210600|DLA^DLA^GLIMS||||
SPM|2|229900281001&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210600|20220802210700||Y
SPM|3|229900281002&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210600|20220802210700||Y
SPM|4|229900281003&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210600|20220802210700||Y
SPM|5|229900281004&GLIMS||CC-BL-N9-0-00-STB0^Na-heparine (groenzwart) 9 ml/Na-heparine/groen, NH 9 ml^GLIMS||||||||9^mL%mL&GLIMS|||||20220802210600|20220802210700||Y
SPM|6|229900281005&GLIMS||CC-BL-S0-0-00-STB0^Stolbloed (rood) 10 ml/Stolbloed/rood, CAT 10 ml^GLIMS||||||||3.5^mL%mL&GLIMS|||||20220802210600|20220802210700||Y
```

```{r Code explanation}
#In this section I'd like to point out some things about the code, what it's for.

#As visible both headers look rather similar. This is because of the standardized way HL7 communicates information. The variables change but the location of those variables are always the same, that is why only some parts of the code are different. What is also apparent is the amount of "|" (pipes) in the code. GLIMS is setup with a table structure. Using the pipes, we tell HL7 to skip variables in order to access the needed variables for the message.

#At each first SPM message there's a line of code referencing a "Non-existing Tube". For this message we use an "OULR22" message, which normally contains all results attached to the sample. Aside from results we would also like to supply information through this message. HL7 only accepts the message if all information is linked to the sample. This means that every PID, OBR and ORC cluster also needs an SPM. We supply the results down below through multiple SPM's. So in order to circumvent the requirement of another SPM in the cluster we created a dummy SPM.
```

```{r final code, eval = FALSE}
#The header is used in combination with the final code to create the message that will be sent. I didn't make the code below and therefore also don't understand it fully. For completions sake I have added the final code below.

STRING Extended,Tube,sOrdsumm,sMat,sLastloc,BepalingenUitBuis,sCompact,sOutline,sMatdes,sI,sMatnum,sLowObjT,snow,b,sStval; 
STRING sHeader,Pin,sPatName,sPatData,sDOB,P,sSex,sOrdnr,sStNr,sreqlist,sStPan,ssel,sSpecType,sMatVar,sDumSpecNr,SEGMENT,sVol,SextId; 
Integer I,vanaf,Aantal;

DateTime DTnow;

Result rStudie;
Order ord;
Specimen Spmn;
Material mat;

Object obj;
obj :=.Object;

/*variabele*/
p:="|";
B:=Chr(10);
SEGMENT:="";

sLowObjT :=DateTimeToString(ord.ReceiptTime,"%Y%m%d%H%M")+"00";
DTnow := DateAndTimeToDateTime(Today(),Now());
sNow :=DateTimeToString(DTnow,"%Y%m%d%H%M")+"00";
sOrdnr:=.InternalId;
sDumSpecNr:=Substr(sOrdnr,4,-1);
sPatData:=IfKnownString(Expand("Person",obj.Person().Id,Chr(123)+"<PatData \Fm=%FL[-%SL]|[%BD]|[%SX]"+Chr(125),?));
sPatName:=Entry(1,sPatData,P);
sDOB:=DateToString(obj.BirthDate(),"%Y%m%d");
PIN := IfKnownString(obj.PIN("UMCU_I"));
sExtId:=IfKnownString(ord.ExternalId);
sStNr:=ord.Agent.InternalId;
sSEX:=Entry(3,sPatData,P);

/*Specialized OOPEN SPECIMEN functionality*/ 
/*OpenSpecimen needs english character for Female*/
IF sSEX="V" THEN sSEX:="F";ENDIF;
/*OpenSpecimen structuur kan geen dubbele studies verwerken aan 1 pin
StudiePins mogen daarom niet. Bij studie PIN of afwezigheid van PIN wordt externe ID gebruikt.
Indien er ook geen externe ID is wordt de pin een combinatie Studienummer en ordernummer*/
IF Index(Obj.Person().SpouseLastName,"Studie")>0 THEN PIN:="";ENDIF;
/*IF SextId+PIN ="" THEN SextId :=sStNr+sOrdnr; ENDIF;*/
If PIN <> "" THEN PIN := PIN+"^^^UMCU_I";ENDIF;
	
	         /*HEADER MSH+PID+Dummyspecimen is nodig voor compiler*/	
sHeader :="MSH|^~\&|Glims|UMC-Utrecht|OpenSpecimen|UMC-Utrecht|"+snow+"||OUL^R22|000012627500|P|2.5|||NE|AL||8859/15"+B;
sHeader :=sHeader +"PID|1||"+Pin+"|"+sExtId+"|"+sPatName+"^^^^L||"+sDOB+"|"+sSex+"||||||||||||||||N||||||N"+B;
sHeader :=sHeader +"SPM|1|"+sDumSpecNr+"000&GLIMS||CC-BL-DUM-0-00-STB0^Nonexisting^Tube^GLIMS||||||||0^mL&mL&GLIMS|||||"+sLowObjT+"|"+snow+"||Y"+B;
			/*Studie SEGMENT*/
IF ord.IsRequested("studie", TRUE)THEN
	rStudie:=ord.Result("Studie", "Initial", "Validated");
	sStval:=rStudie.RawValue;
	sStNr:=ord.Agent.InternalId;
	sReqList:=ord.Attribute("requestlist");
	sStPan:="";
	I :=1;
		While sStPan=""
		Do
		sSel:=Entry(I,sreqlist,",");
		If index(sSel,"studie")>0 THEN
		sStPan:=sSel;
		ENDIF;
		I:=I+1;
		Done;
/*als er geen Studie mnemonic in de order zit is er geen opbouw van Segment.*/
SEGMENT:="OBR|1||"+sOrdnr+"^GLIMS|"+sStPan+"^"+sStval+"^GLIMS|||"+sLowObjT+"|||||||||LISDLA^Glims - Kcl&&Glims - Kcl^^^^^^hcpr^UMCU_I||||||"+snow+"||CDL|F||^^^"+sLowObjT+"^^R"+B;
SEGMENT:=SEGMENT+"ORC|SC||"+sOrdnr+"^GLIMS||CM||^^^"+sLowObjT+"^^R||"+snow+"|||LISDLA^Glims - Kcl&&Glims - Kcl^^^^^^hcpr^UMCU_I|"+sStNr+"^^^^^^^^^^GLIMS||||CDL^CDL^GLIMS"+B;
SEGMENT:=SEGMENT+"OBX|1|ST|Studie^Studie^GLIMS||"+sStval+"|||-|||F|||"+sLowObjT+"|DLA^DLA^GLIMS||||"+B;
ENDIF;


I :=1;
Spmn := ord.GetSpecimen(?,?);
		/*Body SEGMENT*/
/*Alle Root Specimens worden afgelopen. */
While Spmn <> ?
DO
mat:=Spmn.Material;
If mat.IsRootMaterial THEN
	sI:=IntegerToString(I+1,"%d");
    sMat         := mat.Mnemonic;
       sSpecType  :="A5,B2,BM,C2,C4,C5g,DIV,E0,E2,E6,EG4,ET6,FP,FV,HA,L0,L4,LB3,LG3,LI,N6,N9,OK,S0,S1,SG4,SG5,SP,SV,UP,UV";
       sMatVar    :=Entry(3,sMat,"-");
       If Lookup(sMatVar,sSpecType,",")=0 THEN sMat:=Replace(sMat,sMatVar,"DIV"); ENDIF;
	sMatdes	:=Replace(mat.Description(),"|","/");
	sMatnum	:=spmn.InternalId;
	svol:=FractionalToString(Spmn.Material.MaximalSize,"%7G");	 	IF sVol=? THEN sVol :="0";ENDIF;
svol:= Replace(svol," ","")+"^mL%mL&GLIMS";

	sOrdsumm:=ord.Summary(ResultStatus["INITIAL"], ResultStatus["Discontinued"], "Mnemonic", "Intern", FALSE, "<@>", "Compact");
    sLastloc            := IfKnownString(Spmn.LastLocation);
    Vanaf             := Index(sOrdsumm,(sMat+B));
    BepalingenUitBuis := Substr(sOrdsumm,Vanaf,-1);
    BepalingenUitBuis := Substr(BepalingenUitBuis, Index(BepalingenUitBuis,B)+1,-1);
    BepalingenUitBuis := Substr(BepalingenUitBuis, 1,Index(BepalingenUitBuis,B)-1);
    Aantal            := NumEntries(BepalingenUitBuis,"<@>");

SEGMENT:=SEGMENT+"SPM|"+sI+"|"+sMatnum+"&GLIMS||"+sMat+"^"+sMatdes+"^GLIMS||||||||"+sVol+"|||||"+sLowObjT+"|"+snow+"||Y"+B;
ENDIF;
Spmn :=ord.GetSpecimen(Spmn,?);
I:=I+1;
Done;
/*De Header en Body worden samengevoegd and als HL7 verstuurd.*/
Return sHeader+SEGMENT;
```